### PR TITLE
feat: added arduino pro to list

### PR DESCRIPTION
**Pull request by seehma**
please review, iam not sure about all entries here. I think it should be added to make this list more complete...

### CODE REVIEW

**Comment by zantiu** [comment]
Some questions:
- Which IDE did you consider? Since we're comparing PLC/DCS systems we should consider their PLC IDE
- Has the 'plain text' changed? In this (older) video I think Jakob still mentions that the ST is not stored as plain text
- You mention a small fee for download. But I checked for the PLC IDE and see the fee is a suggestion. So no footnote needed here.

For the links we should use the dedicated PRO page: https://www.arduino.cc/pro/
Which is different than the 'professional' page in your commit.

**Comment by seehma** [comment]
- you are right, i didnt find the correct download link in the first place
- iam not sure if it has changed, i added a footnote for this (i installed it and tested a bit)
Iam not sure what you mean with "which IDE", i was talking about the Arduino Pro products. The initial trigger was a post from Jakob on LinkedIn, i think it was a comment, i remembered that those guys are now also existing in this automation-control space and therefore wanted to add them here.

**Comment by seehma** [comment]
done

**Comment by zantiu** [comment]
Yes Arduino Pro can be added.

They list different IDE's: https://www.arduino.cc/pro/platform-software/
It should be the PLC IDE since that's what we focus on in this table.
We should make this clear. Maybe add it as 'Ardruino PRO PLC', and also add the above link in the description?

To get the checkmark for plain text the textual languages (ST) should be stored without XML.
I understand this is not the case? Codesys 3.5 also doesn't do that so there's no checkmark there either.

Did you check the CLI? Can you build and download with it without needing to start the IDE?

**Comment by seehma** [comment]
Sure, its fine! Please remember that iam not an arduino pro user and maybe we find someone else to 100% complete this entry.
- i added an additional line for the IDE and the link
- removed the checkmark for plain-text and added a cross with a footnote (like the beckhoff entry)
- changed the headline of the entry-description
- added a link to arduino-cli-github repo which is mentioned in their pro docs

Iam not 100% sure if you can do every task for a complete ci/cd system but there are a lot of commands and some where compile, load,...

**Comment by zantiu** [comment]
This is the CLI docs:
https://arduino.github.io/arduino-cli/0.35/
However I don't see it allows building a project developed with the PLC IDE.
Suggest to put a question mark until it is clarified. Like this we already have the Arduino entry at least.

Can you do so? And also resolve the confict so I can merge?

**Comment by seehma** [comment]
done, should be ok right now?

**Comment by zantiu** [comment]
Squashed & Merged.

Yes we can put HMI & SCADA in a separate file. But let's first focus on finishing the PLC & DCS table.

**Pull request merged**
