### PR TITLE
Update Beckhoff information

### PR DESCRIPTION
**Pull request by dbrowngm**
Added "YES" under open docs and HW independent for Beckhoff.

Open docs:  a huge portion of documents for Beckhoff software and hardware are available for free with no login via the Infosys (infosys.bechhoff.com).  The search is horrendous and the general layout is bad but it's there!

HW independent:  TwinCAT can run on almost any computer that can run Windows and also BSD (and even more through virtualization).  The licensing is expensive on non-Beckhoff hardware but it can do it.  I have personally done this in a production environment with no issues.

### CODE REVIEW

**Comment by dfreiberger** [comment]
I would suggest that we put yes under "CLI", but with a caveat. You can do everything that can be done in TwinCAT with the AutomationInterface, and that can easily be done through CLI (PowerShell). The caveat is that it has a dependency on the full development environment (Visual Studio Shell) which can make CI/CD pipelines painful to create and maintain.

**Comment by zantiu** [comment]
I updated directly since I just switched to emojis. (open docs + HW independent)

**Comment by zantiu** [comment]
@dfreiberger can you open a separate issue for the CLI?

**Comment by zantiu** [comment]
CLI here: https://github.com/SASE-Space/ot-openness-comparison/pull/9

**Pull request closed without merging**
